server:
  port: 8082
spring:
  application:
    name: department
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true

  eureka:
    instance:
      client:
        serviceUrl.defaultZone=http://localhost:8761/eureka/
